name: chatify

description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ^3.11.4


dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  # Firebase
  firebase_core:
  firebase_messaging:


  # Networking
  dio: ^5.9.2


  # State Management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^11.0.0


  # Functional Programming
  dartz: ^0.10.1


  # Dependency Injection
  get_it: ^9.2.1


  # Localization
  easy_localization: ^3.0.8


  # Security
  dart_jsonwebtoken: ^3.4.1
  crypto: ^3.0.7


  # Local Storage
  hive_flutter: ^1.1.0
  path_provider: ^2.1.6


  # Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0


  # Utils
  recase: ^4.1.0


  # Permissions
  permission_handler: ^12.0.3


  # Network Status
  connectivity_plus: ^7.2.0


  # Socket
  web_socket_channel: ^3.0.3


  # Routing
  go_router: ^17.3.0

  equatable: ^2.1.0



dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0

  # Code Generation
  build_runner: ^2.15.1
  freezed: ^3.2.5
  json_serializable: ^6.14.0

  flutter_secure_storage: ^10.3.1

  web_socket_channel: ^3.0.3

  jwt_decoder: ^2.0.1



flutter:

  uses-material-design: true


  fonts:

    - family: Poppins

      fonts:

        - asset: assets/fonts/poppins/Poppins-Regular.ttf


        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500


        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600


        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700